spring.application.name=backend


app.jwt.secret=t9dRXm9YCi3wDYiGNOiBqMgPcINVqN9Gbbw6KnZDODSThLwMNL0J64i1u5A4SFWpZkMGjeRuHUHI2J1QkFWb4O
app.jwt.expiration=86400000


HttpOnly = true
Secure = false
SameSite = none


server.port=8000

spring.datasource.url=jdbc:postgresql://localhost:5432/postmind
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# for decoration in console
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect